#!/usr/bin/env python3
"""Generate outputs/gain_feasibility.md from the live sources.

    python scripts/report_gain_feasibility.py

Every number in the report is read at generation time -- the actuator config out
of the upstream source with ``ast``, the commanded gains out of the clip
metadata, the torque peaks out of the curated logs. Nothing is transcribed, so
the report cannot drift away from the repo it describes.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from motion_toolkit.clips import JOINT_PERM, raw_channels
from motion_toolkit.session import load_session
from motion_toolkit.window import detect_motion
from sim import isaac_cfg as IC
from sim.replay import FALLBACK, ReplayMode, torque_headroom
from terrain_toolkit.paths import (
    CURATED_ROOT,
    GAIN_FEASIBILITY_MD,
    ISAAC_PROBE_JSON,
    SKILL_CLIPS_META_JSON,
    SKILL_CLIPS_NPZ,
)


def main() -> int:
    cfg = IC.load()
    meta = json.loads(SKILL_CLIPS_META_JSON.read_text())
    z = np.load(SKILL_CLIPS_NPZ, allow_pickle=False)
    legs = [str(x) for x in z["leg_order"]]
    joints = [str(x) for x in z["joint_order"]]
    _, iso_pose, limits = cfg.ordered(legs, joints)
    rel = cfg.source.relative_to(cfg.source.parents[5])

    L: list = []
    A = L.append
    A("# Can the joint gains be changed at runtime?")
    A("")
    A("Generated by `scripts/report_gain_feasibility.py`. Numbers are read from the")
    A(f"upstream source (`{rel}`), the clip archive and the curated logs at generation time.")
    A("")
    A("**Short answer: yes, and the repo already does it.** The Go2 actuators in this fork are")
    A("*explicit* — the PD runs in Python during `write_data_to_sim()` and reads")
    A("`actuator.stiffness` at that moment — so assigning new gains takes effect on the next")
    A("step with no PhysX call. `_apply_domain_randomization()` uses exactly this mechanism")
    A("today, per-env and per-joint. The open question is not *whether* but *how often*, and")
    A("the answer to that is: less often than expected, because the log's gain schedule is")
    A("near-constant within a skill.")
    A("")
    A("There is a second, larger problem that this investigation turned up and that gain")
    A("scheduling does **not** solve — see [Torque headroom](#torque-headroom).")
    A("")

    A("## What was read from the source")
    A("")
    A("These are facts, checked on this machine with no Isaac Lab installed.")
    A("")
    A("| fact | value | where |")
    A("|---|---|---|")
    A(f"| Isaac Lab | `isaaclab 6.1.14` / `isaacsim 6.0.0.1` (Isaac Lab 3.0), Python 3.12 | `environment_eureka_lab6.yml`, `pip_freeze_eureka_lab6.txt` |")
    A(f"| sim step | `dt = {cfg.sim_dt}` s | `{rel}` |")
    A(f"| decimation | `{cfg.decimation}` | same |")
    A(f"| **control rate** | **{cfg.control_hz:.0f} Hz** | derived; matches the clips' `lo` rate exactly |")
    A(f"| action scale | `{cfg.action_scale}` | position target = `action_scale x action + default_joint_pos` |")
    for a in cfg.actuators:
        A(f"| actuator `{a.name}` | `{a.cls}` kp={a.stiffness} kd={a.damping} effort={a.effort_limit} Nm vel={a.velocity_limit} rad/s | same |")
    A(f"| actuators explicit? | **{cfg.all_explicit}** | `IdealPDActuator` computes torque in Python, not PhysX |")
    A("| runtime gain change | **already in use** | `LeggedRobot._apply_domain_randomization()`: `act.stiffness *= motor_strength[0][:, ids]`, per-env per-joint tensors |")
    A("| gain DR range | `motor_strength_range = [0.8, 1.2]`, `randomize_motor = True` | `legged_robot_config.py` |")
    A("| effort target used? | **no** — only `set_joint_position_target` | `LeggedRobot._apply_action()` |")
    A("")
    A("The important one is the actuator class. The fork *deliberately* moved off `DCMotorCfg`")
    A("to `IdealPDActuatorCfg` (\"DCMotor's torque-speed derating is an extra constraint the")
    A("original never had, and it drove the policy into a crawling local optimum\") — which means")
    A("the PD is Python-side by design, and Python-side is precisely what makes gains schedulable.")
    A("")
    A("**The stock Isaac Lab Go2 gains (kp 25 / kd 0.5) are not what this project uses.** An")
    A("earlier note in `outputs/skill_clips.md` compared against those; it is corrected here. The")
    A(f"fork uses kp {cfg.actuators[0].stiffness:g} / kd {cfg.actuators[0].damping:g}, which is *exactly* what the")
    A("position-controlled log sessions commanded. WALK and TROT need no gain change at all.")
    A("")

    A("## What still has to be probed")
    A("")
    A("Isaac Lab is not installed here, so these are asserted from the API and must be checked")
    A("before they are relied on. `scripts/probe_isaac_actuator.py` checks all of them in about")
    A("a minute and writes `" + ISAAC_PROBE_JSON.name + "`; it measures `robot.data.applied_torque`")
    A("rather than testing whether a method exists.")
    A("")
    A("| # | assertion | how the probe decides |")
    A("|---|---|---|")
    A("| 1 | the actuators are explicit at runtime, not just by class name | doubles `stiffness`, expects the applied torque magnitude to double |")
    A("| 2 | assigning `actuator.stiffness` (not just `*=`) is honoured | same test |")
    A("| 3 | `set_joint_effort_target` **adds** to the PD term rather than replacing it | commands +5 Nm, expects `applied_torque` to shift by +5 |")
    A("| 4 | `write_joint_stiffness_to_sim` exists and is the *implicit* path, irrelevant here | calls it, records accept/raise |")
    A("| 5 | torque is clipped at `effort_limit` with no torque-speed curve | commands an absurd position error, reads the plateau |")
    A("")
    A("If (3) comes back \"replaces\" or \"ignored\", every feed-forward mode is out and the fallback")
    A("chain below drops straight to `position`.")
    A("")

    A("## Do the gains actually need to change every step?")
    A("")
    A("| clip | log kp (hip/thigh/calf) | log kd | sim kp/kd | tau_ff RMS (Nm) | position-controlled? |")
    A("|---|---|---|---|---|---|")
    f3 = lambda v: " / ".join(f"{x:g}" for x in v)
    for name, c in meta["clips"].items():
        g = c["gains"]
        A(f"| `{name}` | {f3(g['kp'])} | {f3(g['kd'])} | {cfg.actuators[0].stiffness:g} / {cfg.actuators[0].damping:g} | "
          f"{f3([round(x,2) for x in g['tau_ff_rms']])} | {'yes' if g['position_controlled'] else '**no**'} |")
    A("")
    A("Two clips need nothing: WALK and TROT were recorded at the config's own gains with zero")
    A("feed-forward. Two need the real treatment: RUN sits at kp 13/3/2 — a calf gain of 2 Nm/rad")
    A("is a nearly free leg — and JUMP carries ~10-14 Nm RMS of feed-forward.")
    A("")
    A("Within a skill the gains are *piecewise constant*, not continuously varying: the sport")
    A("controller switches between a handful of discrete levels. That is why option (a) below")
    A("costs so little.")
    A("")

    A("## The four replay modes")
    A("")
    A("Implemented in `sim/replay.py`, selected with `verify_skill_replay.py --mode`. A requested")
    A("mode is resolved against what the installed Isaac Lab supports and the **resolved** mode is")
    A("recorded with the result, so a run can never be reported under a mode it did not use.")
    A("")
    A("| mode | gains | tau_ff | needs | loses |")
    A("|---|---|---|---|---|")
    A("| `torque` | per step, from the clip | per step | runtime gain write + effort target | nothing |")
    A("| `fixed-gain` **(a)** | one pair per skill, set before sim start | per step | effort target only | the within-skill gain schedule |")
    A("| `ff-only` **(b)** | config kp 40 / kd 1 | per step | effort target only | the whole gain schedule |")
    A("| `position` | config kp 40 / kd 1 | none | nothing | everything torque-driven |")
    A("")
    A("Fallback chain: " + " → ".join(f"`{m.value}`" for m in
      [ReplayMode.TORQUE, ReplayMode.FIXED_GAIN, ReplayMode.FF_ONLY, ReplayMode.POSITION]) + ".")
    A("")
    A("### (a) per-skill fixed gains — the recommended fallback")
    A("")
    A("Set the actuator gains on the `ArticulationCfg` before the sim starts, one pair per skill,")
    A("and re-set them on a skill switch. Cheap, needs no runtime API, and because the log's gains")
    A("are piecewise constant per skill it loses very little. The cost: a skill switch now has a")
    A("gain discontinuity, which the real robot also had, so this is arguably more faithful than")
    A("interpolating.")
    A("")
    A("For the planner this is a *good* fit — it already models skills as discrete with a switch")
    A("delay, so \"switch the gains with the skill\" falls out of the existing state machine rather")
    A("than being bolted on.")
    A("")
    A("### (b) feed-forward torque path")
    A("")
    A("`Articulation.set_joint_effort_target()` feeds `control_action.joint_efforts`, which")
    A("`IdealPDActuator.compute()` adds to `kp*e_pos + kd*e_vel` before clipping. Position target")
    A("and effort target can be set on the same step. **Asserted, probe item 3.** The fork never")
    A("uses it, so nothing in-repo confirms it.")
    A("")
    A("### (c) parameter-based gait generator — the real fallback")
    A("")
    A("If neither gains nor feed-forward can be applied, clip replay cannot reproduce RUN and")
    A("there is no point pretending otherwise. Drop to a parameterised gait: contact schedule")
    A("(period, duty, phase offsets) plus a swing trajectory, with the parameters taken from")
    A("`outputs/skill_profile.csv` rather than invented.")
    A("")
    A("The repo already leans this way — `scripts/record_gait.py` records \"a 4xT 0/1 step pattern")
    A("(the WHEN)\" from a trained policy \"to ground the saytap step-pattern library in a real")
    A("controller\". A gait generator driven by the *measured* contact schedule is the same idea")
    A("with the curated logs as the source instead of a policy. The clips already carry the")
    A("contact signal, so the WHEN is in hand; only the WHERE would need building.")
    A("")
    A("This costs the most and buys the most robustness: it has no convention problem, no gain")
    A("problem and no torque problem, because it never replays a recorded trajectory.")
    A("")

    A("## Torque headroom")
    A("")
    A("This is the finding that gain scheduling does not fix.")
    A("")
    A("`IdealPDActuator` clips torque at a static `effort_limit`. The real robot went past it.")
    A("")
    A("| clip | joint | peak logged (Nm) | p99.9 | sim limit | peak/limit |")
    A("|---|---|---|---|---|---|")
    any_over = False
    for name, c in meta["clips"].items():
        sess_dir = next(p for p in CURATED_ROOT.glob("*/" + c["session"]))
        sess = load_session(sess_dir)
        win = detect_motion(sess)
        ch, _ = raw_channels(sess)
        tau = ch["tau"][win.mask][:, JOINT_PERM]
        for h in torque_headroom(tau, [l if l is not None else np.inf for l in limits], joints):
            any_over |= h.over
            A(f"| `{name}` | {h.joint_type} | {h.peak_logged_nm:.2f} | {h.p999_logged_nm:.2f} | "
              f"{h.limit_nm:.2f} | {h.ratio:.2f}× {'**OVER**' if h.over else ''} |")
    A("")
    if any_over:
        A("RUN's thigh and JUMP's thigh and calf exceed the configured clip by 10-20%. The logged")
        A("`tau` is the firmware's estimate (`tau_est`), not a load-cell reading, so treat the")
        A("magnitude as approximate — but the direction is not in doubt, and the hip/thigh limit")
        A("of 23.7 Nm is annotated in the source as coming from a spec sheet.")
        A("")
        A("Consequence: **the sim robot is weaker than the one that produced these clips.** A jump")
        A("replay will fall short of 0.25 m, and `STEP_JUMP_MAX` measured on the probes will be a")
        A("property of the sim robot.")
        A("")
        A("That is the *correct* thing to calibrate — the planner is evaluated in sim, so a limit")
        A("that describes the sim robot is the limit the planner needs. What must not happen is")
        A("raising `effort_limit` for the calibration run only: that would calibrate against a")
        A("robot the evaluation never instantiates, and it is exactly the kind of per-arm tweak")
        A("`CLAUDE.md` §2 rules out. Record the gap; do not close it.")
        A("")
        A("Check it directly with `verify_skill_replay.py --headroom`, and watch")
        A("`torque_saturated_frac` in the replay results.")
    A("")

    A("## Recommendation")
    A("")
    A("1. Run `scripts/probe_isaac_actuator.py` first. Everything below branches on it.")
    A("2. Verify WALK and TROT in `position` mode. Their gains already match the config, so a")
    A("   failure there is a convention bug, not a gain bug — a clean separation of concerns.")
    A("3. Verify RUN in `torque` mode, falling back to `fixed-gain`. Expect it to fall short on")
    A("   forward speed regardless, because of the thigh torque clip.")
    A("4. Treat JUMP as the least trustworthy replay: it is over the clip on two joint groups.")
    A("5. Keep (c) costed. If probe item 3 fails, it is not a fallback, it is the plan.")
    A("")
    A("## Correction applied elsewhere")
    A("")
    A("`outputs/skill_clips.md` and `motion_toolkit/README.md` previously compared the log's gains")
    A("against Isaac Lab's *stock* Go2 defaults (kp 25 / kd 0.5). That is a different robot from")
    A(f"the one this project instantiates. Both now quote the fork's kp {cfg.actuators[0].stiffness:g} / kd {cfg.actuators[0].damping:g}.")
    A("")
    A("The conclusion did not change \u2014 RUN was recorded at kp 13/3/2, and 40 is further from")
    A("that than 25 was, so a position replay of RUN is *more* wrong than first stated. But one")
    A("consequence did change, in the useful direction: **WALK and TROT need no gain handling at")
    A("all**, because kp 40 / kd 1 with zero feed-forward is exactly what they were recorded at.")
    A("")

    GAIN_FEASIBILITY_MD.parent.mkdir(parents=True, exist_ok=True)
    GAIN_FEASIBILITY_MD.write_text("\n".join(L) + "\n")
    print(f"wrote {GAIN_FEASIBILITY_MD} ({len(L)} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
